version: "3"

services:
  app-web-owner:
    image: owner_qr
    build:
      context: .
      dockerfile: Dockerfile
    container_name: owner_qr
    ports:
      - "8000:8000"
    volumes:
      - ~/volumes/django:/var/opt/django-owner-qr
