# Generated by Django 4.2.6 on 2024-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
