# Generated by Django 4.2.6 on 2024-09-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customer_email_verified_customer_google_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
