# Generated by Django 4.2.6 on 2024-09-10 11:31

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_google_picture_customer_google_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to=myApp.models.upload_to_qr),
        ),
    ]
