# Generated by Django 4.2.6 on 2024-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_unassignedqr_shippingaddress_qrcodeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='qrcodeorder',
            name='items',
            field=models.ManyToManyField(to='myApp.item'),
        ),
    ]
