# Generated by Django 4.2.6 on 2024-09-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='myApp.shippingaddress'),
        ),
    ]
