# Generated by Django 4.2.6 on 2024-09-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_customer_default_shipping_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodeorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='qrcodeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrcodeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Proceso'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
