# Generated by Django 4.2.6 on 2024-09-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_promotionalqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalqr',
            name='associated_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.item'),
        ),
    ]
