# Generated by Django 4.2.6 on 2024-09-13 13:30

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_promotionalqr_associated_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalqr',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=myApp.models.upload_to_promotional_qr),
        ),
    ]
