# Generated by Django 4.2.6 on 2024-09-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_promotionalqr_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalqr',
            name='activation_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='promotionalqr',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotionalqr',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
