# Generated by Django 4.2.6 on 2024-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_promotionalqr_activation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalqr',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
