# Generated by Django 4.2.6 on 2025-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_qrcode_remove_promotionalqr_associated_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='activation_email',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
